<?php

namespace Database\Seeders;

use App\Models\Penduduk;
use App\Models\User;
use Illuminate\Database\Seeder;

class PendudukSeeder extends Seeder
{
    public function run(): void
    {
        $dataPenduduk = [
            [
                'nama' => 'Budi Santoso',
                'email' => 'budi@sideska.test',
                'nik' => '3404010101850001',
                'no_kk' => '3404010101850001',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1985-01-01',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Petani',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 01',
                'rt' => '001',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567801',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Slamet Santoso',
                'nama_ibu' => 'Siti Aminah',
            ],

            [
                'nama' => 'Siti Aminah',
                'email' => 'siti@sideska.test',
                'nik' => '3404016102880002',
                'no_kk' => '3404010101850001',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1988-02-21',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_hubungan_keluarga' => 'Istri',
                'golongan_darah' => 'A',
                'alamat' => 'Jl. Sekartejo No. 01',
                'rt' => '001',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567802',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Ahmad',
                'nama_ibu' => 'Maryam',
            ],

            [
                'nama' => 'Andi Pratama',
                'email' => 'andi@sideska.test',
                'nik' => '3404011505100003',
                'no_kk' => '3404010101850001',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2010-05-15',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'SMP/Sederajat',
                'pekerjaan' => 'Pelajar',
                'status_hubungan_keluarga' => 'Anak',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 01',
                'rt' => '001',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567803',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Budi Santoso',
                'nama_ibu' => 'Siti Aminah',
            ],

            [
                'nama' => 'Dewi Lestari',
                'email' => 'dewi@sideska.test',
                'nik' => '3404015508120004',
                'no_kk' => '3404015508120004',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1992-08-15',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Guru',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'B',
                'alamat' => 'Jl. Sekartejo No. 12',
                'rt' => '002',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567804',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Suyanto',
                'nama_ibu' => 'Wartini',
            ],

            [
                'nama' => 'Rudi Hartono',
                'email' => 'rudi@sideska.test',
                'nik' => '3404012007790005',
                'no_kk' => '3404012007790005',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1979-07-20',
                'jenis_kelamin' => 'L',
                'agama' => 'Kristen',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Wiraswasta',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'AB',
                'alamat' => 'Jl. Sekartejo No. 20',
                'rt' => '002',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567805',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Hartono',
                'nama_ibu' => 'Rukmini',
            ],

            [
                'nama' => 'Lina Marlina',
                'email' => 'lina@sideska.test',
                'nik' => '3404016503900006',
                'no_kk' => '3404012007790005',
                'tempat_lahir' => 'Klaten',
                'tanggal_lahir' => '1990-03-25',
                'jenis_kelamin' => 'P',
                'agama' => 'Kristen',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'Diploma',
                'pekerjaan' => 'Karyawan Swasta',
                'status_hubungan_keluarga' => 'Istri',
                'golongan_darah' => 'A',
                'alamat' => 'Jl. Sekartejo No. 20',
                'rt' => '002',
                'rw' => '001',
                'dusun' => 'Dusun Krajan',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567806',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Sutrisno',
                'nama_ibu' => 'Lastri',
            ],

            [
                'nama' => 'Agus Setiawan',
                'email' => 'agus@sideska.test',
                'nik' => '3404011201820007',
                'no_kk' => '3404011201820007',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1982-01-12',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Peternak',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 31',
                'rt' => '003',
                'rw' => '001',
                'dusun' => 'Dusun Tengah',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567807',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Sutopo',
                'nama_ibu' => 'Sumarni',
            ],

            [
                'nama' => 'Wahyu Nugroho',
                'email' => 'wahyu@sideska.test',
                'nik' => '3404010506940008',
                'no_kk' => '3404010506940008',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1994-06-05',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Programmer',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'B',
                'alamat' => 'Jl. Sekartejo No. 45',
                'rt' => '003',
                'rw' => '001',
                'dusun' => 'Dusun Tengah',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567808',
                'status_kependudukan' => 'Pendatang',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Nugroho',
                'nama_ibu' => 'Sri Wahyuni',
            ],

            [
                'nama' => 'Nurul Hidayah',
                'email' => 'nurul@sideska.test',
                'nik' => '3404014909970009',
                'no_kk' => '3404014909970009',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1997-09-09',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Perawat',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 52',
                'rt' => '004',
                'rw' => '001',
                'dusun' => 'Dusun Tengah',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567809',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Hasyim',
                'nama_ibu' => 'Fatimah',
            ],

            [
                'nama' => 'Fajar Ramadhan',
                'email' => 'fajar@sideska.test',
                'nik' => '3404012201050010',
                'no_kk' => '3404012201050010',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2005-01-22',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pelajar',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'A',
                'alamat' => 'Jl. Sekartejo No. 60',
                'rt' => '004',
                'rw' => '001',
                'dusun' => 'Dusun Tengah',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567810',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Herman',
                'nama_ibu' => 'Yuliana',
            ],

            [
                'nama' => 'Maya Sari',
                'email' => 'maya@sideska.test',
                'nik' => '3404015804860011',
                'no_kk' => '3404015804860011',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1986-04-18',
                'jenis_kelamin' => 'P',
                'agama' => 'Hindu',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'B',
                'alamat' => 'Jl. Sekartejo No. 72',
                'rt' => '005',
                'rw' => '001',
                'dusun' => 'Dusun Ngudi',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567811',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Made Sari',
                'nama_ibu' => 'Komang Ayu',
            ],

            [
                'nama' => 'Dimas Saputra',
                'email' => 'dimas@sideska.test',
                'nik' => '3404011406020012',
                'no_kk' => '3404011406020012',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2002-06-14',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Karyawan Swasta',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 80',
                'rt' => '005',
                'rw' => '001',
                'dusun' => 'Dusun Ngudi',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567812',
                'status_kependudukan' => 'Pendatang',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Slamet',
                'nama_ibu' => 'Wati',
            ],

            [
                'nama' => 'Rina Wulandari',
                'email' => 'rina@sideska.test',
                'nik' => '3404016208950013',
                'no_kk' => '3404016208950013',
                'tempat_lahir' => 'Klaten',
                'tanggal_lahir' => '1995-08-22',
                'jenis_kelamin' => 'P',
                'agama' => 'Katolik',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'Diploma',
                'pekerjaan' => 'Bidan',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'AB',
                'alamat' => 'Jl. Sekartejo No. 91',
                'rt' => '006',
                'rw' => '001',
                'dusun' => 'Dusun Ngudi',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567813',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Wawan',
                'nama_ibu' => 'Endang',
            ],

            [
                'nama' => 'Hendra Wijaya',
                'email' => 'hendra@sideska.test',
                'nik' => '3404011007750014',
                'no_kk' => '3404011007750014',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1975-05-10',
                'jenis_kelamin' => 'L',
                'agama' => 'Buddha',
                'status_perkawinan' => 'Kawin',
                'pendidikan' => 'SMA/Sederajat',
                'pekerjaan' => 'Pengusaha',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'A',
                'alamat' => 'Jl. Sekartejo No. 105',
                'rt' => '006',
                'rw' => '001',
                'dusun' => 'Dusun Ngudi',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567814',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Wijaya',
                'nama_ibu' => 'Lestari',
            ],

            [
                'nama' => 'Sari Puspita',
                'email' => 'sari@sideska.test',
                'nik' => '3404014303980015',
                'no_kk' => '3404014303980015',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1998-03-03',
                'jenis_kelamin' => 'P',
                'agama' => 'Konghucu',
                'status_perkawinan' => 'Belum Kawin',
                'pendidikan' => 'S1',
                'pekerjaan' => 'Desainer',
                'status_hubungan_keluarga' => 'Kepala Keluarga',
                'golongan_darah' => 'O',
                'alamat' => 'Jl. Sekartejo No. 117',
                'rt' => '007',
                'rw' => '001',
                'dusun' => 'Dusun Ngudi',
                'kewarganegaraan' => 'WNI',
                'no_hp' => '081234567815',
                'status_kependudukan' => 'Tetap',
                'disabilitas' => 'Tidak',
                'nama_ayah' => 'Purnomo',
                'nama_ibu' => 'Sri Lestari',
            ],
        ];

        foreach ($dataPenduduk as $data) {
            $user = User::create([
                'name' => $data['nama'],
                'email' => $data['email'],
                'password' => 'password',
                'role' => 'masyarakat',
            ]);

            Penduduk::create([
                'user_id' => $user->id,
                'foto' => null,
                'nik' => $data['nik'],
                'no_kk' => $data['no_kk'],
                'nama' => $data['nama'],
                'tempat_lahir' => $data['tempat_lahir'],
                'tanggal_lahir' => $data['tanggal_lahir'],
                'jenis_kelamin' => $data['jenis_kelamin'],
                'agama' => $data['agama'],
                'status_perkawinan' => $data['status_perkawinan'],
                'pendidikan' => $data['pendidikan'],
                'pekerjaan' => $data['pekerjaan'],
                'status_hubungan_keluarga' => $data['status_hubungan_keluarga'],
                'golongan_darah' => $data['golongan_darah'],
                'alamat' => $data['alamat'],
                'rt' => $data['rt'],
                'rw' => $data['rw'],
                'dusun' => $data['dusun'],
                'kewarganegaraan' => $data['kewarganegaraan'],
                'no_hp' => $data['no_hp'],
                'status_kependudukan' => $data['status_kependudukan'],
                'disabilitas' => $data['disabilitas'],
                'nama_ayah' => $data['nama_ayah'],
                'nama_ibu' => $data['nama_ibu'],
            ]);
        }
    }
}
